// front-react-vite/src/components/AuthorCard/index.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import dogWithGlass from '@/assets/dog with glass.jpg'

const AuthorCard = () => {
  return (
    <div style={{ width: 300 }} className="card shadow-sm p-3 mb-5 bg-white border-solid border-black">
      <div className="card-image">
        <img
          style={{
            height: 100,
            width: '100%',
            maxWidth: 100,
          }}
          src={`${dogWithGlass}`}
          alt="주인장"
        />
      </div>
      <div className="card-content">
        <div className="media">
          <div className="media-content">
            <Link href="/">
                <h3> KKY's BLOG</h3>
            </Link>
            <a className="icon" href="https://www.linkedin.com/in/ki-young-kwon-168381193/">
              <i className="fab fa-linkedin fa-2x"></i>
            </a>
            &nbsp;
            <a className="icon" href="https://github.com/kkywalk2">
              <i className="fab fa-github fa-2x"></i>
            </a>
          </div>
        </div>

        <div className="content">
          안녕하세요 웹개발 관련 공부를 위해 만들고 있는 블로그 입니다.
          <br />
        </div>
      </div>
    </div>
  );
};

export default AuthorCard;

// front/src/components/AuthorCard.vue
<template>
  <div class="card">
    <div class="card-image">
      <figure class="image is-3by3">
        <image src="../assets/logo.png" alt="주인장" />
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <a class="plain" href="/">
            <p class="title is-4"> KKY's BLOG</p>
          </a>
          <br />
          <a class="icon" href="https://www.linkedin.com/in/ki-young-kwon-168381193/">
            <i class="fab fa-linkedin fa-2x"></i>
          </a>&nbsp;
          <a class="icon" href="https://github.com/kkywalk2">
            <i class="fab fa-github fa-2x"></i>
          </a>
        </div>
      </div>

      <div class="content">
        안녕하세요 웹개발 관련 공부를 위해 만들고 있는 블로그 입니다.
        <br />
      </div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style>
</style>
